apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconsumer
  namespace: solution-vision
spec:
  selector:
    matchLabels:
      app: kafkaconsumer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaconsumer
    spec:
     containers:
      - name: kafkaconsumer
        image: manibsccs89/kafkaconsumer:2.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: KafkaServerName
          value: my-release-kafka.default.svc.cluster.local:9092
        - name: KafkaTopicName
          value: test
