---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanosubscriber1
  namespace: solution
spec:
  selector:
    matchLabels:
      app: nanosubscriber1
  replicas: 1
  template:
    metadata:
      labels:
        app: nanosubscriber1
    spec:
     containers:
      - name: nanosubscriber1
        image: manibsccs89/nanosubscriber:5.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NanoMqServerName
          value: nanomqbrokersvc.coreandcommon.svc.cluster.local
