apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaproducer
  namespace: crosscontamination
spec:
  selector:
    matchLabels:
      app: kafkaproducer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaproducer
    spec:
     containers:
      - name: kafkaproducer
        image: manibsccs89/kafkaproducer:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: KafkaServerName
          value: my-release-kafka.default.svc.cluster.local:9092
        - name: KafkaTopicName
          value: test
