apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuronex-pvc-cc
  namespace: crosscontamination
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi

