apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-p
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: blob-fuse-p
  volumeName: pv-blob-p
