apiVersion: v1

kind: PersistentVolume

metadata:

  annotations:

    pv.kubernetes.io/provisioned-by: blob.csi.azure.com

  name: pv-blob

spec:

  capacity:

    storage: 10Gi

  accessModes:

    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: blob-fuse

  mountOptions:

    - -o allow_other

    - --file-cache-timeout-in-seconds=120

  csi:

    driver: blob.csi.azure.com

    readOnly: false

    # make sure volumeid is unique for every storage blob container in the cluster

    # the # character is reserved for internal use

    volumeHandle: pepsicotest_images

    volumeAttributes:

      resourceGroup: pep-edap-eiotp-data-dev-eus-01-rg

      storageAccount: pepeiotpdveus1pubsa

      containerName: images

    nodeStageSecretRef:

      name: azure-secret

      namespace: default 