apiVersion: storage.k8s.io/v1

kind: StorageClass

metadata:

  name: blob-fuse

provisioner: blob.csi.azure.com

parameters:

  resourceGroup: pep-edap-eiotp-data-dev-eus-01-rg

  storageAccount: pepeiotpdveus1pubsa

  containerName: images

reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion

volumeBindingMode: Immediate

allowVolumeExpansion: true

mountOptions:

  - -o allow_other

  - --file-cache-timeout-in-seconds=120

  - --use-attr-cache=true

  - --cancel-list-on-mount-seconds=60  # prevent billing charges on mounting

  - -o attr_timeout=120

  - -o entry_timeout=120

  - -o negative_timeout=120

  - --cache-size-mb=1000 