kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
#  annotations:
#    nfs.io/storage-path: "./" # not required, depending on whether this annotation was shown in the storage class description

spec:
  storageClassName: nfs-client3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Deployment

metadata:
  name: nfs-busybox
  namespace: coreandcommon

spec:
  replicas: 1

  selector:
    name: nfs-busybox

  template:
    metadata:
      labels:
        name: nfs-busybox

    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /data/index.html; hostname >> /data/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: manibsccs89/nanopublisher:5.0.0
        env:
        - name: NanoMqServerName
          value: emqxbrokersvc.coreandcommon.svc.cluster.local
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: /data
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: test-claim
