---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopublisher
  namespace: crosscontamination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanopublisher
  template:
    metadata:
      labels:
        app: nanopublisher
    spec:
      containers:
      - env:
        - name: NanoMqServerName
          value: emqxbrokersvc.coreandcommon.svc.cluster.local
        image: manibsccs89/nanopublisher:5.0.0
        imagePullPolicy: IfNotPresent
        name: nanopublisher
      volumeMounts:
      - mountPath: /data
        name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: test-claim
