apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ekuiper-pvc
  namespace: coreandcommon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ekuiper-plugins-pvc
  namespace: coreandcommon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekuiper
  namespace: coreandcommon
spec:
  selector:
    matchLabels:
      app: ekuiper
  replicas: 1
  template:
    metadata:
      labels:
        app: ekuiper
    spec:
     securityContext:
          fsGroup: 1001
          runAsUser: 1001
          runAsGroup: 1001
     initContainers:
      - name: logshipper
        image: alpine:latest
        restartPolicy: Always
        command: ['sh', '-c', 'touch /kuiper/plugins/logs.txt']
        volumeMounts:
         - name: ekuiper-plugin-v
           mountPath: /kuiper/plugins
     containers:
      - name: ekuiper
        image: lfedge/ekuiper:1.11.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: ekuipervol
           mountPath: /kuiper/data
         - name: ekuiper-plugin-v
           mountPath: /kuiper/plugins
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
        env:
        - name: MQTT_SOURCE__DEFAULT__SERVER
          value: 'tcp://emqxbrokersvc.coreandcommon.svc.cluster.local:1883'
        - name: KUIPER__BASIC__IGNORECASE
          value: 'false'
        ports:
         - containerPort: 9081
           name: management
           protocol: TCP
     volumes:
      - name: ekuipervol
        persistentVolumeClaim:
          claimName: ekuiper-pvc
      - name: ekuiper-plugin-v
        persistentVolumeClaim:
          claimName: ekuiper-plugins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ekuipersvc
  namespace: coreandcommon
spec:
  type: ClusterIP
  selector:
    app: ekuiper
  ports:
    - name: management
      port: 9081
      targetPort: 9081
      protocol: TCP
