apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekuiper
  namespace: coreandcommon
spec:
  selector:
    matchLabels:
      app: ekuiper
  replicas: 1
  template:
    metadata:
      labels:
        app: ekuiper
    spec:
     containers:
      - name: ekuiper
        image: lfedge/ekuiper:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: ekuipervolv
           mountPath: /opt/ekuiper/persistence
        env:
        - name: MQTT_SOURCE__DEFAULT__SERVER
          value: 'tcp://broker.emqx.io:1883'
        - name: KUIPER__BASIC__IGNORECASE
          value: 'false'
        ports:
         - containerPort: 9081
           name: management
           protocol: TCP
     volumes:
      - name: ekuipervolv
        persistentVolumeClaim:
          claimName: emqxbroker-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ekuipersvc
  namespace: coreandcommon
spec:
  type: ClusterIP
  selector:
    app: ekuiper
  ports:
    - name: management
      port: 9081
      targetPort: 9081
      protocol: TCP
