apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqxbroker-pvc
  namespace: coreandcommon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqxbroker
  namespace: coreandcommon
spec:
  selector:
    matchLabels:
      app: emqxbroker
  replicas: 1
  template:
    metadata:
      labels:
        app: emqxbroker
    spec:
     containers:
      - name: emqxbroker
        image: emqx/emqx:5.0.20
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: emqxbrokervolv
           mountPath: /opt/emqx/persistence
        ports:
            - containerPort: 1883
              name: tcp-port
              protocol: TCP
            - containerPort: 8083
              name: ws-port
              protocol: TCP
            - containerPort: 8084
              name: wss-port
              protocol: TCP
            - containerPort: 8883
              name: ssl-port
              protocol: TCP
            - containerPort: 18083
              name: mgnt-port
              protocol: TCP
     volumes:
      - name: emqxbrokervolv
        persistentVolumeClaim:
          claimName: emqxbroker-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: emqxbrokersvc
  namespace: coreandcommon
spec:
  type: ClusterIP
  selector:
    app: emqxbroker
  ports:
    - name: tcp-port
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: ws-port
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: wss-port
      port: 8084
      targetPort: 8084
      protocol: TCP
    - name: ssl-port
      port: 8883
      targetPort: 8883
      protocol: TCP
    - name: mgnt-port
      port: 18083
      targetPort: 18083
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: emqxbrokerlb
  namespace: coreandcommon
spec:
  type: LoadBalancer
  externalIPs:
    - 20.235.16.30
  selector:
    app: emqxbroker
  ports:
    - name: mgnt-portal
      port: 18083
      targetPort: 18083
      protocol: TCP
