---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopublisher
  namespace: crosscontamination
spec:
  selector:
    matchLabels:
      app: nanopublisher
  replicas: 1
  template:
    metadata:
      labels:
        app: nanopublisher
    spec:
     containers:
      - name: nanopublisher
        image: manibsccs89/nanopublisher:5.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NanoMqServerName
          value: emqxbrokersvc.coreandcommon.svc.cluster.local
     volumeMounts:
      - name: nfs
        mountPath: ./abhinav
     volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-claim-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-cinder
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-cinder-container
    volumeMounts:
    - mountPath: /test-cinder
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
     claimName: nfs-claim-pvc
