apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-pvc-v11
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-clientv3
---
kind: Pod
apiVersion: v1
metadata:
  name: manikandan-pod
spec:
  containers:
  - name: manikandan-pod
    image: busybox:stable
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/manikandanSUCCESS"
    volumeMounts:
      - name: nfsazure
        mountPath: "/mnt"
  volumes:
    - name: nfsazure
      persistentVolumeClaim:
        claimName: nfs-claim-pvc-v11
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: "/mnt"
      name: nfsazure
  volumes:
   - name: nfsazure
     persistentVolumeClaim:
       claimName: nfs-claim-pvc-v11
