---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopublisher
  namespace: crosscontamination
spec:
  selector:
    matchLabels:
      app: nanopublisher
  replicas: 1
  template:
    metadata:
      labels:
        app: nanopublisher
    spec:
     containers:
      - name: nanopublisher
        image: manibsccs89/nanopublisher:5.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NanoMqServerName
          value: emqxbrokersvc.coreandcommon.svc.cluster.local

     volumeMounts:
      - name: nfs
        mountPath: /data
     volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: test-claim	 
