---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client3
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: sc-nginx
  name: sc-nfs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-nginx
  template:
    metadata:
      labels:
        app: sc-nginx
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-claim-pvc
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nfs 
          mountPath: /usr/share/nginx/html 
